name: Build pdf from tex source with lualatex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # Fix the version to avoid breaking changes.
      # You can use 'v3' to use the latest version on the v3.
    - uses: xu-cheng/latex-action@v3.1.0
      with:
        root_file: main.tex
        compiler: lualatex
    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}.pdf
        path: main.pdf
