name: Build all contents

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          apk add make
          make main.pdf
    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}
        path: main.pdf
