name: Build all contents

on:
  workflow_call:
    inputs:
      built_artifact_name:
        description: 'The name of the built artifact'
        required: false
        default: "built-${{ github.sha }}"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xu-cheng/texlive-action@v2
      with:
        scheme: full
        run: |
          apk add make
          make main.pdf
    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.built_artifact_name }}
        path: main.pdf
        retention-days: 1
