name: Build all contents

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # Fix the version to avoid breaking changes.
    - uses: xu-cheng/latex-action@3.1.0
      with:
        root_file: main.tex
        compiler: lualatex
    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}
        path: main.pdf
