name: Build pdf from tex source with lualatex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build pdf
      uses: docker://ghcr.io/latex-lsp/texlive-full:latest
      with:
        args: lualatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 -output-format=pdf main.tex
    - name: Upload pdf
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}.pdf
        path: main.pdf
