name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/builder.yaml
  auto-merge-update-bib:
    needs: build
    uses: yamatolab/wf-update-bibliography/.github/workflows/merge_pr.yaml@main
