name: Deploy to GitHub Pages and release page

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/builder.yaml
    with:
      built_artifact_name: "built-contents-${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: "built-contents-${{ github.sha }}"
          path: ./dist
      - name: Update name of pdf file
        run: mv ./dist/main.pdf ./dist/262201296_SugiuraWataru_master-thesis.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*
