name: Deploy to GitHub Pages and release page

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/builder.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: built_contents
          path: ./dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*
